astropy/asdf-astropy

- MANIFEST.in
- asdf_astropy/integration.py
- asdf_astropy/resources/manifests/astropy-1.0.yaml
- asdf_astropy/resources/schemas/coordinates/angle-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/earthlocation-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/frames/baseframe-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/frames/cirs-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/frames/fk4-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/frames/fk4noeterms-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/frames/fk5-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/frames/galactic-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/frames/galactocentric-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/frames/gcrs-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/frames/icrs-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/frames/icrs-1.1.0.yaml
- asdf_astropy/resources/schemas/coordinates/frames/itrs-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/frames/precessedgeocentric-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/latitude-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/longitude-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/representation-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/skycoord-1.0.0.yaml
- asdf_astropy/resources/schemas/coordinates/spectralcoord-1.0.0.yaml
- asdf_astropy/resources/schemas/fits/fits-1.0.0.yaml
- asdf_astropy/resources/schemas/table/table-1.0.0.yaml
- asdf_astropy/resources/schemas/time/timedelta-1.0.0.yaml
- asdf_astropy/resources/schemas/transform/units_mapping-1.0.0.yaml
- asdf_astropy/resources/schemas/units/equivalency-1.0.0.yaml
- asdf_astropy/tests/test_integration.py
- scripts/generate_manifest.py
- setup.cfg
This PR adds the astropy schemas to this repo, a manifest file for their associated tags, and a plugin for accessing them from asdf.
The schemas are mostly unchanged, but I did make two fixes:
- Renamed time-1.0.0 to timedelta-1.0.0 to match its tag
- Updated `$ref` properties containing tags to be schema ids instead
Tests will not pass with the prototype converters still in place, but that'll get fixed in the next PR.
> Add astropy-specific schemas to repo

- .github/workflows/asdf_astropy_ci.yml
- README.rst
- docs/conf.py
This PR attempts to replace all mention of `master` to `main` in this repository. This should be reviewed and merged right after the maintainer has renamed the default branch.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
This is part of #12
> MNT: Replace master with main

- .github/workflows/ci.yml
- README.rst
- docs/conf.py
This is a copy of #13, which didn't make it into the commit history of `main` because I renamed the default branch in a goofy way.
> Replace master with main

- asdf_astropy/_astropy_init.py
This is probably leftover from package template. This package does not use the `astropy` configuration system at all.
Also see astropy/astropy#11497
> MNT: Remove unused astropy config code

- asdf_astropy/converters/coordinates/angle.py
- asdf_astropy/converters/coordinates/earth_location.py
- asdf_astropy/converters/coordinates/frame.py
- asdf_astropy/converters/coordinates/representation.py
- asdf_astropy/converters/coordinates/sky_coord.py
- asdf_astropy/converters/coordinates/spectral_coord.py
- asdf_astropy/converters/coordinates/tests/helpers.py
- asdf_astropy/converters/coordinates/tests/test_angle.py
- asdf_astropy/converters/coordinates/tests/test_earth_location.py
- asdf_astropy/converters/coordinates/tests/test_frame.py
- asdf_astropy/converters/coordinates/tests/test_representation.py
- asdf_astropy/converters/coordinates/tests/test_sky_coord.py
- asdf_astropy/converters/coordinates/tests/test_spectral_coord.py
- asdf_astropy/converters/transform/core.py
- asdf_astropy/converters/utils.py
- asdf_astropy/extensions.py
- asdf_astropy/resources/manifests/astropy-1.0.0.yaml
- tox.ini
This PR adds converter support for the following tags:
```
tag:astropy.org:astropy/coordinates/angle-1.0.0
tag:astropy.org:astropy/coordinates/latitude-1.0.0
tag:astropy.org:astropy/coordinates/longitude-1.0.0
tag:astropy.org:astropy/coordinates/earthlocation-1.0.0
tag:astropy.org:astropy/coordinates/frames/cirs-1.0.0
tag:astropy.org:astropy/coordinates/frames/fk4-1.0.0
tag:astropy.org:astropy/coordinates/frames/fk4noeterms-1.0.0
tag:astropy.org:astropy/coordinates/frames/fk5-1.0.0
tag:astropy.org:astropy/coordinates/frames/galactic-1.0.0
tag:astropy.org:astropy/coordinates/frames/galactocentric-1.0.0
tag:astropy.org:astropy/coordinates/frames/gcrs-1.0.0
tag:astropy.org:astropy/coordinates/frames/icrs-1.0.0
tag:astropy.org:astropy/coordinates/frames/icrs-1.1.0 …
```
> Add converter support for coordinates tags

- .github/workflows/ci.yml
You are using a deprecated version of `codecov-action`, see https://github.com/codecov/codecov-action for more details. xref astropy/astropy#12245
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
> MNT: Update codecov-action version to v2

- asdf_astropy/converters/transform/tests/test_transform.py
- setup.cfg
The asdf-transform-schemas package has been released, so we no longer need to install it from GitHub.  I'm also removing a test that has been made irrelevant by the change to asdf-transform-schemas to remove the ASDF Standard version requirements.
> Use release version of asdf-transform-schemas

- CHANGES.rst
- asdf_astropy/converters/table/table.py
The schema allows meta to be missing, but the Converter implementation assumes that it will be present.  My mistake!
> Fix bug in table deserializer when meta is absent from the ASDF

- CHANGES.rst
- asdf_astropy/converters/transform/core.py
- asdf_astropy/converters/transform/tests/test_transform.py
Allows for `input_unit_equivalencies` to be written and read for models.
Note that, this mirrors the changes in astropy/astropy#10198.
> Serialization of model unit equivalencies

- CHANGES.rst
- asdf_astropy/converters/transform/mappings.py
- asdf_astropy/resources/schemas/transform/units_mapping-1.0.0.yaml
In asdf-format/asdf-transform-schemas#33, the `inputs` and `outputs` properties were formally added to the transform schema. This conflicts with the use of those fields in the `units_mapping` schema for other purposes. This PR fixes the bugs that result from this.
Note that this replicates the bugfix in PR astropy/astropy#12800.
> Bugfix for `units_mapping` asdf schema.

- .github/workflows/ci.yml
- tox.ini
Astropy 5 only supports python 3.8+ which means using new astropy features will break the Python 3.7 CI. Hence, we are dropping it here.
> Remove python 3.7 from CI

- CHANGES.rst
- asdf_astropy/converters/transform/tests/test_transform.py
- asdf_astropy/testing/helpers.py
The `assert_model_equal` function will be useful to other projects.
> Move assert_model_equal to testing helpers module

- .github/workflows/ci.yml
- .gitignore
- CHANGES.rst
- asdf_astropy/extensions.py
The `Schechter1D` model was introduced to astropy in astropy/astropy#13116. Since, asdf-format/asdf-transform-schemas#54 was merged there is now a schema for `Schechter1D`. This PR adds the corresponding converter to handle this model.
Fixes #66.
> Add converter for Schechter1D model

- CHANGES.rst
- docs/asdf-astropy/details.rst
- docs/asdf-astropy/example.rst
- docs/asdf-astropy/manifest.rst
- docs/asdf-astropy/migrating.rst
- docs/asdf-astropy/quickstart.rst
- docs/asdf-astropy/schemas.rst
- docs/asdf-astropy/table.rst
- docs/conf.py
- docs/index.rst
- setup.cfg
This PR is to address the issues found in the astropy coordinated package review, see: https://github.com/astropy/astropy.github.com/pull/490#issuecomment-1132239666
- Fixes #75 and Fixes #76 by properly setting minimum python version to 3.8
- Fixes #72 by adding a small quickstart guide
- Fixes #74 by adding notes about the transition of `astropy.io.misc.asdf` to this package
> Updates from astropy coordinated package review

- .pre-commit-config.yaml
- asdf_astropy/converters/transform/compound.py
Applies [`pyupgrade`](https://github.com/asottile/pyupgrade) to asdf-astropy and adds it to the pre-commit hooks. `pyupgrade` is a tool to automatically update the older python syntax to the newer more preferred syntax.
> Apply pyupgrade

- .gitignore
- CHANGES.rst
- asdf_astropy/converters/transform/core.py
- asdf_astropy/converters/transform/properties.py
- asdf_astropy/converters/transform/tests/test_transform.py
- asdf_astropy/extensions.py
- asdf_astropy/testing/helpers.py
This PR adds converters for the bounding_box and compound_bounding_box properties in asdf-transform-schemas.
Closes #38, Closes #60, and closes astropy/astropy#12696
> Converters for `ModelBoundingBox` and `CompoundBoundingBox`

- .pre-commit-config.yaml
- pyproject.toml
In https://github.com/asdf-format/asdf-transform-schemas/pull/69#discussion_r967744284, it was pointed out that autoflake8 was recently archived in favor of autoflake. This PR makes the update here.
> Update from autoflake8 to autoflake

- CHANGES.rst
- asdf_astropy/converters/unit/quantity.py
- asdf_astropy/converters/unit/tests/test_quantity.py
Based on the discussion in astropy/astropy#13864, I found that we need to add the `copy=False` flag to the array constructor and arrange for a more complicated test for `memmap` than we normally require.
resolves astropy/astropy#13864
> Bugfix for `memmap` not working with `Quantity`

- CHANGES.rst
- asdf_astropy/converters/time/tests/test_time.py
- asdf_astropy/converters/time/time.py
This PR returns some pure string outputs from the time converter under some circumstances as requested in #128 reverting some of the changes in #86. With this PR:
- `iso`
- `jyear_str`
- `byear_str`
- `yday`
will be written purely as strings. Before #86 the:
- `isot`
- `jyear`
- `byear`
formats would also be written as pure strings; however, these will no round-trip the format as they would be deserialize as `iso`, `jyear_str`, and `byear_str` formats respectively.
Fixes #128
> Bugfix for time strings

- CHANGES.rst
- asdf_astropy/converters/unit/quantity.py
- asdf_astropy/converters/unit/tests/test_quantity.py
Bugfix so that the `dtype` of a `Quantity` object is preserved.
Fixes #130
> Bugfix for `Quantity.dtype`

- tox.ini
Currently the CI is failing: https://github.com/astropy/asdf-astropy/actions/runs/3673136901.
This appears to be due to some old and unnecessary settings in the `tox.ini` file. This PR removes that setting and cleans out the old unused tox environments.
> Fix failing CI and clean up tox

- .pre-commit-config.yaml
- README.rst
- pyproject.toml
Similar to asdf-format/asdf#1267, this PR introduces using [codespell](https://github.com/codespell-project/codespell) to `asdf-astropy`.
> Start using codespell

- .github/workflows/ci.yml
- CHANGES.rst
- asdf_astropy/converters/transform/tests/test_transform.py
- pyproject.toml
- tox.ini
Adds testing for the oldest declared dependencies of `asdf-astropy`.
> Add oldest testing

- CHANGES.rst
- asdf_astropy/_manifest.py
- asdf_astropy/converters/unit/tests/test_unit.py
- asdf_astropy/converters/unit/unit.py
- asdf_astropy/extensions.py
- asdf_astropy/resources/manifests/astropy-1.0.0.yaml
- asdf_astropy/resources/manifests/units-1.0.0.yaml
Adds support for non-VOunit serialization to a separate tag/schema than VOunits.
Fixes #144
> Add support for non-VOunits

- CHANGES.rst
- asdf_astropy/converters/__init__.py
- asdf_astropy/converters/unit/__init__.py
- asdf_astropy/converters/unit/magunit.py
- asdf_astropy/converters/unit/tests/test_magunit.py
- asdf_astropy/extensions.py
- asdf_astropy/resources/manifests/units-1.0.0.yaml
- asdf_astropy/resources/schemas/units/magunit-1.0.0.yaml
Adds support for `MagUnit` objects for ASDF. See #145 for details.
Note that this PR is based off #142, and so will need to be merged after that one.
Fixes #145
> Support for `MagUnit`

- asdf_astropy/converters/coordinates/tests/test_frame.py
- asdf_astropy/converters/fits/tests/test_fits.py
- asdf_astropy/converters/table/tests/test_table.py
- asdf_astropy/converters/time/tests/test_time.py
- asdf_astropy/converters/transform/tests/test_transform.py
- asdf_astropy/converters/unit/tests/test_quantity.py
- asdf_astropy/converters/unit/tests/test_unit.py
asdf.tests.helpers is being deprecated in:
https://github.com/asdf-format/asdf/pull/1440
This PR updates the uses of asdf.tests.yaml_to_asdf to use asdf.testing.yaml_to_asdf.
> change asdf.tests.helpers use to asdf.testing.helpers

- CHANGES.rst
- asdf_astropy/converters/table/tests/test_table.py
- asdf_astropy/converters/transform/tests/test_transform.py
- asdf_astropy/io/tests/test_io.py
- asdf_astropy/testing/helpers.py
- docs/asdf-astropy/api.rst
Moves all the `assert` testing functions to `asdf_astropy.testing.helpers` and document that module.
Fixes #162
> Move helper functions to `asdf_astropy.testing.helpers`

- .github/workflows/ci.yml
- CHANGES.rst
- asdf_astropy/integration.py
- pyproject.toml
Astropy has dropped python 3.8, asdf-astropy needs to follow suite.
> Drop Python 3.8 support

- asdf_astropy/converters/unit/tests/test_unit.py
The `create_vounits` and `create_non_vounits` generate many duplicate results resulting in many duplicate tests
Here's a few results from `create_vounits`:
```
Unit("fvox"), Unit("fvox"), Unit("fvox"), Unit("avox"), Unit("avox"), Unit("avox"), Unit("zvox"), Unit("zvox"), Unit("zvox")
```
This PR uses a `set` instead of a `list` to remove the duplicates. Prior to this PR `create_vounits` generated 3858 items, removing duplicates with this PR it now generates 1601.
> remove duplicate units in unit converter tests

- CHANGES.rst
- asdf_astropy/converters/coordinates/representation.py
Astropy recently moved a few classes:
https://github.com/astropy/astropy/pull/14792
moved several classes previously in `astropy.coordinates.representation` to submodules. This broke the `RepresentationConverter`. This PR adds the new class paths (and retains the old ones for backwards compatibility).
~https://github.com/astropy/astropy/pull/14763
moved several `Geodetic` classes into `astropy.coordinates.representation`. The `__all__` of this module is used within the asdf-astropy tests to collect classes to test the `RepresentationConverter`. It does not appear that these `Geodetic` classes are currently supported by asdf-astropy so the test was updated to ignore these classes from the list of classes to test.~
> Update `RepresentationConverter` for new class paths in astropy dev

- CHANGES.rst
- asdf_astropy/converters/coordinates/angle.py
- asdf_astropy/converters/coordinates/earth_location.py
- asdf_astropy/converters/coordinates/frame.py
- asdf_astropy/converters/coordinates/representation.py
- asdf_astropy/converters/coordinates/sky_coord.py
- asdf_astropy/converters/coordinates/spectral_coord.py
- asdf_astropy/converters/fits/fits.py
- asdf_astropy/converters/table/table.py
- asdf_astropy/converters/time/time.py
- asdf_astropy/converters/time/time_delta.py
- asdf_astropy/converters/transform/compound.py
- asdf_astropy/converters/transform/functional_models.py
- asdf_astropy/converters/transform/mappings.py
- asdf_astropy/converters/transform/math_functions.py
- asdf_astropy/converters/transform/polynomial.py
- asdf_astropy/converters/transform/properties.py
- asdf_astropy/converters/transform/rotations.py
- asdf_astropy/converters/transform/spline.py
- asdf_astropy/converters/transform/tabular.py
- asdf_astropy/converters/unit/equivalency.py
- asdf_astropy/converters/unit/magunit.py
- asdf_astropy/converters/unit/quantity.py
- asdf_astropy/converters/unit/tests/test_magunit.py
- asdf_astropy/converters/unit/unit.py
> Attempt 2 Make class variables immutable

- CHANGES.rst
- pyproject.toml
This is superfluous and was never needed.
It appears to have come from copy/paste from the old astropy package template
> Drop oldest supported numpy from build-system

- CHANGES.rst
- asdf_astropy/_manifest.py
- asdf_astropy/tests/test_integration.py
- tox.ini
asdf-astropy currently implements converters for a number of core asdf types/tags. These converters are registered with an extension that is created in part using the core manifests provided by asdf-standard:
https://github.com/astropy/asdf-astropy/blob/38f76e19b85bf44b7d83d8f76f6705121e1f49ad/asdf_astropy/extensions.py#L520-L539
Because these extensions use the extension uri defined in the core manifests yet do not fully support all tags, this creates an issue where files can be written with incomplete extension history.
For example, using current development version of asdf, writing an empty tree produces the following file:
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, …
```
> generate a unique uri for extensions that convert core types

- CHANGES.rst
- asdf_astropy/converters/__init__.py
- asdf_astropy/converters/table/__init__.py
- asdf_astropy/converters/table/table.py
- asdf_astropy/converters/table/tests/test_table.py
- asdf_astropy/extensions.py
- asdf_astropy/integration.py
- asdf_astropy/resources/manifests/astropy-1.1.0.yaml
- asdf_astropy/resources/schemas/table/ndarraymixin-1.0.0.yaml
- asdf_astropy/resources/schemas/table/table-1.1.0.yaml
asdf 3.0 will warn when a ndarray subclass instance is converted using the ndarray converter as is done in the `test_ndarray_mixin` test:
https://github.com/astropy/asdf-astropy/blob/153b31c848750c8dabe2ac566caea333a47975a6/asdf_astropy/converters/table/tests/test_table.py#L216-L222
This PR adds `NdarrayMixinConverter` (and a corresponding tag and schema) to both prevent the warning and to allow round-tripping `NdarrayMixin` instances.
This PR updates the table schema (1.1.0) to reference the new ndarraymixin schema. These updates are included in a new version (1.1.0) of the astropy extension.
> add NdarrayMixin support, bump astropy extension version to 1.1.0

- CHANGES.rst
- asdf_astropy/converters/coordinates/angle.py
see: https://github.com/astropy/astropy/pull/15220
This PR addresses the currently failing devdeps testing. See the run for the current pre-commit PR for the failures fixed in this PR:
https://github.com/astropy/asdf-astropy/actions/runs/6302302107/job/17109199660?pr=206
> update angle class paths in angle converters based on astropy changes

- .github/workflows/ci.yml
- CHANGES.rst
- asdf_astropy/converters/unit/quantity.py
- tox.ini
astropy 6.1 changed the behavior of `copy`:
https://github.com/astropy/astropy/pull/16198
This breaks the `Quantity` converter and was not caught due to the `devdeps` testing against astropy "nightlies" which haven't been updated.
This PR adds a version check against numpy since that is the core source of the error (it looks like astropy will just pass es through `copy` to `array` instead of selectively calling `asarray`).
This PR also updates the CI to:
- remove astropy and transform 'lts' testing since 'lts' no longer exists
- adds a `predeps` job that runs against pre-releases
The masked array failure in the `predeps` should be fixed by:
https://github.com/asdf-format/asdf/pull/1769
which has not yet been released.
> Update `copy` usage in `Quantity` converter to deal with astropy 6.1 changes

- CHANGES.rst
- asdf_astropy/converters/unit/equivalency.py
- asdf_astropy/converters/unit/tests/test_equivalency.py
Equivalencies are serialized by storing the `kwargs`:
https://github.com/astropy/asdf-astropy/blob/1b286108042c1201199e9931cd2a5b52cc57bdce/asdf_astropy/resources/schemas/units/equivalency-1.1.0.yaml#L19
The `factor` keyword argument to `spectral_density` is deprecated in astropy 7.0 which means:
- any file that contains a `spectral_density` that was originally created with a `factor` will produce a warning when loaded
- these files will be unreadable when `factor` is removed
This PR strip `factor` when it's `None` to avoid the deprecation warning for astropy 7 and only tests `factor` for astropy versions older than 7.
> Strip `factor=None` in equivalency converter for spectral density

- .github/workflows/ci.yml
- .readthedocs.yaml
- CHANGES.rst
- pyproject.toml
- tox.ini
This PR drops a few old versions of:
- python, now >=3.10
- numpy, now >=1.24
- astropy, now >=5.2
This PR also fixes the oldestdeps job which appears to have never worked due to a typos, `oldestdep` instead of `oldestdeps` (and `parallels` instead of `parallel`):
https://github.com/astropy/asdf-astropy/blob/dab5b4d73ce3f75e60e5b29e75eb3e811dfd8319/.github/workflows/ci.yml#L103
When it `oldestdeps` working with this PR and the numpy version was bumped the CI showed failures due to the old astropy (5.0.4). These were addressed by bumping astropy to 5.2.0.
Fixes https://github.com/astropy/asdf-astropy/issues/231
> drop py39 try to fix oldestdeps

- CHANGES.rst
- asdf_astropy/converters/unit/tests/test_quantity.py
- pyproject.toml
follow-on to https://github.com/asdf-format/asdf/pull/1797
> replace usages of ``copy_arrays`` with ``memmap`` for ``asdf>=3.1.0``

- asdf_astropy/converters/transform/tests/test_transform.py
The minimum required version of astropy is 5.2. 
https://github.com/astropy/asdf-astropy/blob/9348f899f57114b574b050ea59d3c74b28e498f6/pyproject.toml#L24
This PR removes the `if` check for the following:
https://github.com/astropy/asdf-astropy/blob/9348f899f57114b574b050ea59d3c74b28e498f6/asdf_astropy/converters/transform/tests/test_transform.py#L81
Originally discussed: #235
> Remove `astropy` version check

- .github/workflows/ci.yml
- CHANGES.rst
- asdf_astropy/converters/transform/core.py
- asdf_astropy/converters/transform/properties.py
- asdf_astropy/converters/transform/tests/test_transform.py
- asdf_astropy/extensions.py
- pyproject.toml
- requirements-dev.txt
- tox.ini
Our `oldestdeps` and `devdeps` [CI](https://github.com/astropy/asdf-astropy/actions/runs/10988582459) are failing on main. This PR fixes the CI by:
- removing scipy dev installation. This is an indirect requirement via astropy (we use 0 scipy API). Their nightly wheels are currently broken and given our limited use it seems safe to me to not require a dev scipy version (since the latest released version works with nightly numpy).
- increasing the asdf minimum version. Something with the very old version of jsonschema pulled in by our minimum asdf wasn't playing nice with the CI. I first attempted to bump this to 2.14 but that failed due to a lack of a jsonschema upper pin. 2.14.4 has an upper pin and allows the `oldestdeps` to now pass. 2.14.4 was released Mar 20, 2023 but given the …
> Cleanup, fix CI, remove out-dated version checks

- .github/dependabot.yml
- .github/workflows/changelog.yml
- .github/workflows/ci.yml
- .github/workflows/downstream.yml
- .github/workflows/publish-to-pypi.yml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
> MNT: Use hash for Action workflow versions and update if needed

- asdf_astropy/converters/transform/tests/test_transform.py
astropy added astropy.modeling.functional_models.Lorentz2D see https://github.com/astropy/asdf-astropy/issues/243
This PR adds the unsupported model to the list of unsupported models to fix the devdeps.
This PR does not close the associated issue as we'll need to:
- make a schema
- add the schema to asdf-transform-schemas
- add a converter to this package
so let's leave the issue open to track that work.
> skip Lorentz2D until it can be supported

- CHANGES.rst
- asdf_astropy/extensions.py
- asdf_astropy/integration.py
- asdf_astropy/tests/test_integration.py
asdf-astropy 0.5.0 wrote files with a reported extension_uri containing astropy.org:
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, homepage: 'http://github.com/asdf-format/asdf',
name: asdf, version: 3.3.0}
history:
extensions:
- !core/extension_metadata-1.0.0
extension_class: asdf.extension._manifest.ManifestExtension
extension_uri: asdf://asdf-format.org/core/extensions/core-1.5.0
manifest_software: !core/software-1.0.0 {name: asdf_standard, version: 1.1.1}
software: !core/software-1.0.0 {name: asdf, version: 3.3.0}
- !core/extension_metadata-1.0.0
extension_class: asdf_astropy._manifest.CompoundManifestExtension
extension_uri: …
```
> register blank extensions for old files with modified extension uris

- .pre-commit-config.yaml
These default to weekly and every week we get an automatic PR to update ruff. This reduces the frequency of automatic updates to monthly to reduce the pace at which PRs become out-of-date due to weekly ruff updates.
> reduce autoupdate to monthly

- CHANGES.rst
- asdf_astropy/extensions.py
- pyproject.toml
This PR adds support for the new asdf-transform and asdf-coordinates schemas. It will be brought out of draft when those packages are released and the pins can be set.
> Enable support for new transform and coordinates schemas

- asdf_astropy/converters/time/tests/test_time.py
Astropy added a new `galexsec` time format. This is not listed in the time schema and will require an asdf-standard update and release to support (see https://github.com/astropy/asdf-astropy/issues/292).
Until then, this PR skips testing `galexsec` to fix our devdeps.
> skip galexsec time format test
