astropy/asdf-astropy

README.rst, asdf_astropy/converters/transform/tabular.py, asdf_astropy/converters/transform/tests/test_transform.py, docs/asdf-astropy/index.rst, docs/conf.py, docs/index.rst, setup.cfg, tox.ini
Updated the tox environemnts. The tests run now locally.
One test with the astropy LTS release fails. I suspect a commit which fixed it did not propagate to the release but we need to track this down and if so include it in the next LTS patch.
=> fix tox envs

asdf_astropy/converters/helpers.py, asdf_astropy/converters/transform/compound.py, asdf_astropy/converters/transform/tabular.py, asdf_astropy/resources/schemas/coordinates/angle-1.0.0.yaml, asdf_astropy/resources/schemas/fits/fits-1.0.0.yaml
This was originally #7 but it was inadvertently closed when I renamed master --> main in a goofy way.
=> Address comments from PR #5

asdf_astropy/_astropy_init.py
Follow up of #17 
After I opened that PR, I was told more could be removed in another channel, so here it is.
=> MNT: Simplified _astropy_init.py more

asdf_astropy/converters/transform/tests/test_transform.py, asdf_astropy/converters/unit/equivalency.py, asdf_astropy/converters/unit/quantity.py, asdf_astropy/converters/unit/tests/test_equivalency.py, asdf_astropy/converters/unit/tests/test_quantity.py, asdf_astropy/converters/unit/tests/test_unit.py, asdf_astropy/converters/unit/unit.py, asdf_astropy/extensions.py, asdf_astropy/integration.py, asdf_astropy/resources/manifests/astropy-1.0.0.yaml, asdf_astropy/tests/test_integration.py, tox.ini
This PR adds converter support for the following tags:
```
tag:astropy.org:astropy/units/equivalency-1.0.0
tag:stsci.edu:asdf/unit/quantity-1.1.0
tag:stsci.edu:asdf/unit/unit-1.0.0
```
=> Add converter support for unit-related tags

asdf_astropy/conftest.py, asdf_astropy/converters/coordinates/representation.py, asdf_astropy/converters/coordinates/tests/test_angle.py, asdf_astropy/converters/coordinates/tests/test_earth_location.py, asdf_astropy/converters/coordinates/tests/test_frame.py, asdf_astropy/converters/coordinates/tests/test_representation.py, asdf_astropy/converters/coordinates/tests/test_sky_coord.py, asdf_astropy/converters/coordinates/tests/test_spectral_coord.py, asdf_astropy/converters/time/tests/test_time.py, asdf_astropy/converters/time/tests/test_time_delta.py, asdf_astropy/converters/time/time.py, asdf_astropy/converters/time/time_delta.py, asdf_astropy/converters/transform/tests/test_transform.py, asdf_astropy/converters/unit/quantity.py, asdf_astropy/converters/unit/tests/test_equivalency.py, asdf_astropy/converters/unit/tests/test_quantity.py, asdf_astropy/converters/unit/tests/test_unit.py, asdf_astropy/extensions.py, asdf_astropy/testing/helpers.py, asdf_astropy/tests/test_integration.py, tox.ini
This PR adds converter support for the following tags:
```
tag:stsci.edu:asdf/time/time-1.0.0
tag:stsci.edu:asdf/time/time-1.1.0
tag:astropy.org:astropy/time/timedelta-1.0.0
```
=> Add converter support for time tags

asdf_astropy/converters/fits/fits.py, asdf_astropy/converters/fits/tests/test_fits.py, asdf_astropy/converters/table/table.py, asdf_astropy/converters/table/tests/test_table.py, asdf_astropy/extensions.py, asdf_astropy/testing/helpers.py, asdf_astropy/tests/test_integration.py, tox.ini
This PR adds support for the following tags:
```
tag:stsci.edu:asdf/core/column-1.0.0
tag:stsci.edu:asdf/core/table-1.0.0
tag:stsci.edu:asdf/fits/fits-1.0.0
tag:astropy.org:astropy/table/table-1.0.0
tag:astropy.org:astropy/fits/fits-1.0.0
```
=> Add converter support for table and fits tags

.github/workflows/ci.yml, tox.ini
Add python 3.9 and python 3.10 to CI.
=> Add python 3.9 and python 3.10 to CI.

asdf_astropy/extensions.py
=> Add missing baseframe converter

asdf_astropy/converters/transform/core.py, asdf_astropy/converters/transform/tests/test_transform.py
This PR incorporates the following work done on astropy:
https://github.com/astropy/astropy/pull/12381
https://github.com/astropy/astropy/pull/11942
https://github.com/astropy/astropy/pull/11978
Also added an issue to support new models in astropy 5 and added the to the known unsupported models list so that the tests can pass.
=> Catch up to changes in ASDF support in astropy 5.0

CHANGES.rst, asdf_astropy/converters/transform/spline.py, asdf_astropy/converters/transform/tests/test_transform.py, asdf_astropy/extensions.py, setup.cfg
Adds a converter for the schema introduced in asdf-format/asdf-transform-schemas#41.
=> Add a spline1D converter

CHANGES.rst, README.rst, docs/asdf-astropy/details.rst, docs/asdf-astropy/example.rst, docs/asdf-astropy/index.rst, docs/asdf-astropy/install.rst, docs/asdf-astropy/manifest.rst, docs/asdf-astropy/schemas.rst, docs/asdf-astropy/table.rst, docs/index.rst
Starts the process of moving documentation from astropy to asdf-astropy.
Fixes #53
=> Move documentation from astropy to asdf-astropy try 2

asdf_astropy/converters/time/tests/test_time_delta.py, requirements-dev.txt, tox.ini
Fixes a warning raised when using astropy develop version
=> Fix `TimeDelta` warning

.github/workflows/ci.yml
Add `asdf-transform-schemas` testing to CI
=> Add asdf-transform-schemas development testing

CHANGES.rst, CITATION
Add a citation file to resolve #70.
=> Add Citation

asdf_astropy/converters/unit/tests/test_unit.py
Adds testing for an error state to unit converter tests
=> Add error testing to units

CHANGES.rst, asdf_astropy/converters/coordinates/frame.py, asdf_astropy/converters/coordinates/tests/test_frame.py
=> Add support for multiple tags in a single FrameConverter

README.rst
Codecov badge is broken, this fixes it.
=> Update codecov badge

tox.ini
Currently the devdeps related CI tests are failing, likely related to numpy/numpy#21711.
This is an attempt to resolve this issue.
=> Attempt to fix devdeps CI

CHANGES.rst, asdf_astropy/resources/schemas/table/table-1.0.0.yaml, asdf_astropy/resources/schemas/transform/units_mapping-1.0.0.yaml, asdf_astropy/resources/schemas/units/equivalency-1.0.0.yaml
Removes unnecessary tag from schemas to bring these in line with asdf-format/asdf-standard#326.
=> Remove unnecessary tag from schemas

.github/workflows/publish-to-pypi.yml
Test of the permissions added to astropy publish workflow in astropy/astropy#13397.
=> Add permissions to publish CI

asdf_astropy/converters/transform/tests/test_transform.py
Fixes failing CI see here: https://github.com/astropy/asdf-astropy/runs/7982716170?check_suite_focus=true
=> Bugfix for LTS bug

.github/workflows/ci.yml, asdf_astropy/converters/transform/compound.py, asdf_astropy/converters/transform/core.py, asdf_astropy/converters/transform/projections.py, asdf_astropy/converters/transform/properties.py, asdf_astropy/converters/transform/tests/test_transform.py, tox.ini
Increase the test coverage of transforms
=> Increase test coverage of transforms

.github/workflows/ci.yml, .pre-commit-config.yaml, CHANGES.rst, asdf_astropy/__init__.py, asdf_astropy/conftest.py, docs/conf.py, requirements-dev.txt, tox.ini
Switch to running CI with open-astronomy workflow.
=> Switch to open-astronomy workflow

.github/workflows/changelog.yml, .github/workflows/ci.yml, .github/workflows/downstream.yml, .github/workflows/publish-to-pypi.yml
Updates the permissions and publish CI to be in line with astropy/astropy#14026
=> Update Permissions and CI

.github/workflows/ci.yml, asdf_astropy/converters/time/tests/test_time.py, asdf_astropy/converters/transform/tests/test_transform.py, pyproject.toml, tox.ini
Turns warnings into errors for better detection of emerging issues.
=> Turn Warnings into errors

.pre-commit-config.yaml, pyproject.toml
astropy/astropy#14109 reminded me that I have been meaning to switch `asdf-astropy` from using autoflake/flake8 to using ruff with autofixes.  This PR does that.
Thank you @nstarman
=> Switch from flake8 to ruff

.github/workflows/ci.yml, tox.ini
`asdf-astropy`'s tests have gotten really long (a lot of units being tested). This PR speeds up the CI
=> Add parallelism to `asdf-astropy` CI

asdf_astropy/converters/coordinates/tests/test_representation.py
These have not been released by astropy yet.
=> Ignore the geodetic representations
